name: Build KLOR Split Firmware

on:
  push:
    branches:
      - '**'   # every branch
  workflow_dispatch:
    inputs:
      board:
        description: 'Board'
        required: false
        default: '["nice_nano_v2"]'
      shield:
        description: 'Shield(s)'
        required: false
        default: '["klor_left","klor_right"]'
      alphas:
        description: 'Alphas layout'
        required: false
        default: '["QWERTY"]'
      nav:
        description: 'Navigation layout'
        required: false
        default: '["vi"]'
      layers:
        description: 'Layers'
        required: false
        default: '["default"]'
      settings_reset:
        description: 'Settings reset option'
        required: false
        default: '["default"]'

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: ${{ github.event.inputs.board || '["nice_nano_v2"]' }}
      shield: ${{ github.event.inputs.shield || '["klor_left","klor_right"]' }}
      alphas: ${{ github.event.inputs.alphas || '["QWERTY"]' }}
      nav: ${{ github.event.inputs.nav || '["vi"]' }}
      layers: ${{ github.event.inputs.layers || '["default"]' }}
      settings_reset: ${{ github.event.inputs.settings_reset || '["default"]' }}
